# Header
menu:
  首页: /
  归档: /archives

rss: /atom.xml
nav: right
mobile_nav: right

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- userinfo
- category
# - tag
- tagcloud
- archive
- recent_posts
- blogroll

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
background_image: /images/wlop3.jpg
background_title: 图片作者wlop

# favicon
favicon: /images/4.jpg

#Userinfo
author: zero
slogan: 在追赶前人的脚步上努力的Java菜鸟
# avatar: /images/code-title.png
avatar: /images/4.jpg
avatar_title: 祢豆子

# Article code panel: cloud doorframe mac
highlightPanel: doorframe

#Gitment
gitment:
  owner: 
  repo: 
  client_id: 
  client_secret: 

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 

# 友情链接
blogroll:
  小哈博客: https://blog.littleha.cn/

#增加统计字数，阅读时长
# post_wordcount:
#   item_text: true
#   wordcount: true
#   min2read: true
#   totalcount: true
#   separated_meta: true
  